language: node_js
sudo: true
node_js:
- 6.9.1
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: github.com
before_install:
- bash ./.travis/checkout_secret.sh
script:
- gulp build
- gulp dist
- gulp release
branches:
  only:
  - dev
  - release
